function siFigures_make
	global state 

	setStatusString('Making image windows...');
	
	startImageData = int16(zeros(state.internal.linesPerStripe, state.acq.pixelsPerLine));
	axisYStep=1/state.internal.numberOfStripes;
    
    axisPosition = [0 1-axisYStep 1 .125];
    axisOffset = [0 axisYStep 0 0];
	aspectRatio = (state.internal.imageAspectRatioBias*state.acq.scanAmplitudeY/state.acq.scanAmplitudeX); % /(state.acq.linesPerFrame/state.acq.pixelsPerLine);
	
	setupScanImageFigurePositions;
	
	% This loop creates the appropriate images, figures and axes.
	
    channelList=[1:state.init.maximumNumberOfInputChannels 11:10+state.init.maximumNumberOfInputChannels];
    
    state.imaging.internal.figureHandle=cell(length(channelList), 1);
    state.imaging.internal.axisHandle=cell(length(channelList), state.internal.numberOfStripes);
    state.imaging.internal.imageHandle=cell(length(channelList), state.internal.numberOfStripes);
    state.imaging.internal.maxFigureHandle=cell(length(channelList), 1);
    state.imaging.internal.maxAxisHandle=cell(length(channelList), state.internal.numberOfStripes);
    state.imaging.internal.maxImageHandle=cell(length(channelList), state.internal.numberOfStripes);
    state.imaging.internal.compositeAxisHandle=cell(1, state.internal.numberOfStripes);
    state.imaging.internal.compositeImageHandle=cell(1, state.internal.numberOfStripes);

	for channelCounter = channelList
		state.imaging.internal.figureHandle{channelCounter} = figure(...
			'Position', state.windowPositions.(['image' num2str(channelCounter) '_position']), ...
			'doublebuffer', 'off',...
			'KeyPressFcn', 'genericKeyPressFunction', ...
			'Tag',  ['GraphFigure' num2str(channelCounter)], ...
			'Name',  ['Acquisition of Channel ' num2str(channelCounter)], ...
			'NumberTitle', 'off',  ...
			'MenuBar', 'none', ...
			'CloseRequestFcn', 'set(gcf, ''visible'', ''off'')', ...
			'visible', 'off', ...
			'ColorMap', makeColorMap('graySat',8) ...
			);

		state.imaging.internal.maxFigureHandle{channelCounter} = figure(...
			'Position', state.windowPositions.(['maxImage' num2str(channelCounter) '_position']), ...
			'doublebuffer', 'off',...
			'KeyPressFcn', 'genericKeyPressFunction', ...
			'Tag',  ['MaxFigure' num2str(channelCounter)], ...
			'Name',  ['Max Projection of Channel ' num2str(channelCounter)], ...
			'NumberTitle', 'off',  ...
			'MenuBar', 'none', ...
			'CloseRequestFcn', 'set(gcf, ''visible'', ''off'')', ...
			'visible', 'off', ...
			'ColorMap', makeColorMap('graySat',8) ...
			);
        
        for stripeCounter=1:state.internal.numberOfStripes
            state.imaging.internal.axisHandle{channelCounter, stripeCounter} = ...
                axes(...
                'YDir', 'Reverse', ...
                'NextPlot', 'add', ...
                'XLim', [1 state.acq.pixelsPerLine], ...
                'YLim', [1 state.internal.linesPerStripe], ...
                'CLim', [0 1], ...
                'Parent', state.imaging.internal.figureHandle{channelCounter}, ...
                'YTickLabelMode', 'manual', ...
                'XTickLabelMode', 'manual', ...
                'Position', axisPosition-axisOffset*(stripeCounter-1),  ...
                'XTickLabel', [], ...
                'YTickLabel', [], ...
                'ButtonDownFcn', 'figureButtonOverCallback',...
                'xlimmode','manual',...
                'ylimmode','manual',...
                'zlimmode','manual',...
                'climmode','manual',...
                'alimmode','manual' ...
            );
                %'DataAspectRatioMode', 'manual',  ...
                %'DataAspectRatio', [aspectRatio 1 1] ...
  
            state.imaging.internal.imageHandle{channelCounter, stripeCounter} = ...
                image(...
                startImageData, ...
                'CDataMapping', 'Scaled', ...
                'Parent', state.imaging.internal.axisHandle{channelCounter, stripeCounter}, ...
                'ButtonDownFcn', 'figureButtonOverCallback'...
                );

            state.imaging.internal.maxAxisHandle{channelCounter, stripeCounter} = ...
                axes(...
                'YDir', 'Reverse', ...
                'NextPlot', 'add', ...
                'XLim', [1 state.acq.pixelsPerLine], ...
                'YLim', [1 state.internal.linesPerStripe], ...
                'CLim', [0 1], ...
                'Parent', state.imaging.internal.maxFigureHandle{channelCounter}, ...
                'YTickLabelMode', 'manual', ...
                'XTickLabelMode', 'manual', ...
                'Position', axisPosition-axisOffset*(stripeCounter-1),  ...
                'XTickLabel', [], ...
                'YTickLabel', [], ...
                'ButtonDownFcn', 'figureButtonOverCallback',...
                'xlimmode','manual',...
                'ylimmode','manual',...
                'zlimmode','manual',...
                'climmode','manual',...
                'alimmode','manual' ...
            );
                %'DataAspectRatioMode', 'manual',  ...
                %'DataAspectRatio', [aspectRatio 1 1] ...
  
            state.imaging.internal.maxImageHandle{channelCounter, stripeCounter} = ...
                image(...
                startImageData, ...
                'CDataMapping', 'Scaled', ...
                'Parent', state.imaging.internal.maxAxisHandle{channelCounter, stripeCounter}, ...
                'ButtonDownFcn', 'figureButtonOverCallback'...
                );
        
        end
	end
	
	state.imaging.internal.compositeFigureHandle = figure(...
		'Position', state.windowPositions.compositeImage_position, ...
		'doublebuffer', 'off',...
		'KeyPressFcn', 'genericKeyPressFunction', ...
		'Tag',  'CompositeFigure', ...
		'Name',  'Composite', ...
		'NumberTitle', 'off',  ...
		'MenuBar', 'none', ...
		'CloseRequestFcn', 'set(gcf, ''visible'', ''off'')', ...
		'visible', 'off' ...
		);
	
    for stripeCounter=1:state.internal.numberOfStripes
        state.imaging.internal.compositeAxisHandle{stripeCounter} = ...
            axes(...
            'YDir', 'Reverse', ...
            'NextPlot', 'add', ...
            'XLim', [1 state.acq.pixelsPerLine], ...
            'YLim', [1 state.internal.linesPerStripe], ...
            'CLim', [0 1], ...
            'Parent', state.imaging.internal.compositeFigureHandle, ...
            'YTickLabelMode', 'manual', ...
            'XTickLabelMode', 'manual', ...
            'Position', axisPosition-axisOffset*(stripeCounter-1),  ...
            'XTickLabel', [], ...
            'YTickLabel', [], ...
            'ButtonDownFcn', 'figureButtonOverCallback',...
            'xlimmode','manual',...
            'ylimmode','manual',...
            'zlimmode','manual',...
            'climmode','manual',...
            'alimmode','manual' ...
        );
            %'DataAspectRatioMode', 'manual',  ...
            %'DataAspectRatio', [aspectRatio 1 1] ...

        state.imaging.internal.compositeImageHandle{stripeCounter} = ...
            image(...
            startImageData, ...
            'Parent', state.imaging.internal.compositeAxisHandle{stripeCounter}, ...
            'ButtonDownFcn', 'figureButtonOverCallback'...
            );
    end
    
	setStatusString('');
