function siSet_lutSliders
% siSet_lutSliders Activates the right components of the LUT gui depending
% on the imaging configuration
global state gh


for channelCounter = 1:state.init.maximumNumberOfInputChannels
	if state.acq.acquiringChannel(channelCounter) 
		set([gh.imageGUI.(['highPixelValueSlider' num2str(channelCounter)]) ...
			gh.imageGUI.(['lowPixelValueSlider' num2str(channelCounter)]) ...
			gh.imageGUI.(['highPixelValue' num2str(channelCounter)]) ...
			gh.imageGUI.(['lowPixelValue' num2str(channelCounter)]) ...
			gh.imageGUI.(['whiteTag' num2str(channelCounter)]) ...
			gh.imageGUI.(['blackTag' num2str(channelCounter)])] ...
			, 'Enable', 'On');	
		if state.acq.dualLaserMode>1
			set([gh.imageGUI.(['highPixelValueSlider' num2str(10+channelCounter)]) ...
				gh.imageGUI.(['lowPixelValueSlider' num2str(10+channelCounter)]) ...
				gh.imageGUI.(['highPixelValue' num2str(10+channelCounter)]) ...
				gh.imageGUI.(['lowPixelValue' num2str(10+channelCounter)])] ...
				, 'Enable', 'On');			
		else
			set([gh.imageGUI.(['highPixelValueSlider' num2str(10+channelCounter)]) ...
				gh.imageGUI.(['lowPixelValueSlider' num2str(10+channelCounter)]) ...
				gh.imageGUI.(['highPixelValue' num2str(10+channelCounter)]) ...
				gh.imageGUI.(['lowPixelValue' num2str(10+channelCounter)])] ...
				, 'Enable', 'Off');			
		end			
	else
		set([gh.imageGUI.(['highPixelValueSlider' num2str(channelCounter)]) ...
			gh.imageGUI.(['lowPixelValueSlider' num2str(channelCounter)]) ...
			gh.imageGUI.(['highPixelValue' num2str(channelCounter)]) ...
			gh.imageGUI.(['lowPixelValue' num2str(channelCounter)]) ...			
			gh.imageGUI.(['whiteTag' num2str(channelCounter)]) ...
			gh.imageGUI.(['blackTag' num2str(channelCounter)])] ...
			, 'Enable', 'Off');
		set([gh.imageGUI.(['highPixelValueSlider' num2str(10+channelCounter)]) ...
			gh.imageGUI.(['lowPixelValueSlider' num2str(10+channelCounter)]) ...
			gh.imageGUI.(['highPixelValue' num2str(10+channelCounter)]) ...
			gh.imageGUI.(['lowPixelValue' num2str(10+channelCounter)])] ...
			, 'Enable', 'Off');
	end
end
